name: Build

on: 
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'
      
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - run: npm install
    - run: npm run lint
  
  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com 
          git checkout -b release/v${{ vars.MINOR }}
      - name: Test and Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          rm -f package-lock.json
          npm i -g @vercel/ncc
          npm install --production
          npm run build
          #npm exec --yes -- webpack-bundle-analyzer dist/stats dist -O -m static
      - name: Clean files
        run: |
          rm .gitignore
          rm -Rf node_modules/
          rm -Rf .github
          rm index.js
          rm -f dist/stats
          rm -f dist/index.js.map
          rm -f dist/sourcemap-register.js
      - name: Git Create Branch release/v${{ vars.MINOR }} 
        run: |
          git add .
          git commit -m "Auto commit from Github Actions #${{ github.run_id }}"
          git push origin release/v${{ vars.MINOR }} -f

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag_name: v${{ vars.MINOR }}
          release_name: v${{ vars.MINOR }}
          commitish: release/v${{ vars.MINOR }}
          body: Created using automated workflow
      -
        name: Increment minor version
        run: echo "NEW_MINOR=$((${{ vars.MINOR }}+1))" >> $GITHUB_ENV
      -
        name: Update minor version variable
        uses: kroese/set-variable@v4
        with:
          name: 'MINOR'
          value: ${{ env.NEW_MINOR }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
