name: Build

on: 
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - run: npm install
    - run: npm run lint
    - name: Test the action
      uses: ./.
      with:
        name: 'MY_SECRET'
        value: 'Lorem ipsun dolor simit'
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - run: echo ${{secrets.MY_SECRET }} | sed 's/./& /g'
  
  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
           token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com 
          git checkout -b release/v${{ secrets.MINOR }}
      - name: Test and Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm i -g @vercel/ncc
          npm install --production
          npm run build
      - name: Clean files
        run: |
          rm .gitignore
          rm -Rf node_modules/
          rm -Rf .github
          rm index.js
      - name: Git Create Branch release/v${{ secrets.MINOR }} 
        run: |
          git add .
          git commit -m "Auto commit from Github Actions #${{ github.run_id }}"
          git push origin release/v${{ secrets.MINOR }} -f

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag_name: v${{ secrets.MINOR }}
          release_name: v${{ secrets.MINOR }}
          commitish: release/v${{ secrets.MINOR }}
          body: Created using automated workflow
      -
        name: Increment minor version
        run: echo "NEW_MINOR=$((${{ secrets.MINOR }}+1))" >> $GITHUB_ENV
      -
       name: Update minor version
       uses: kroese/set-secret@v3
       with:
         name: 'MINOR'
         value: ${{ env.NEW_MINOR }}
         repository: ${{ github.repository }}
         token: ${{ secrets.REPO_ACCESS_TOKEN }}
