name: Build

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'
      - 'action.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
    - run: npm install
    - run: npm run lint
  
  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
           token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Setup Git
        run: |
          git config user.name kroese
          git config user.email kroese@users.noreply.github.com
          git checkout -b release/v${{ vars.MAJOR }}.${{ vars.MINOR }}
      -
        name: Test and Build
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          rm -f package-lock.json
          npm i -g @vercel/ncc
          npm install --omit=dev
          npm run build
          #npm run build_stats
          #npm exec --yes -- webpack-bundle-analyzer dist/stats dist -O -m static
      -
        name: Clean files
        run: |
          rm .gitignore
          rm -Rf node_modules/
          rm -Rf .github
          rm index.js
          rm -f dist/stats
          rm -f dist/index.js.map
          rm -f dist/index.873.js.map
          rm -f dist/sourcemap-register.js
      -
        name: Create Branch release/v${{ vars.MAJOR }}.${{ vars.MINOR }}
        run: |
          git add .
          git commit -m "Auto commit from Github Actions #${{ github.run_id }}"
          git push origin release/v${{ vars.MAJOR }}.${{ vars.MINOR }} -f
      -
        name: Get previous tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -1)
          echo "previousTag: $name"
          echo "previousTag=$name" >> $GITHUB_ENV
      -
        name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.previousTag }}
          writeToFile: false
          reverseOrder: true
          includeInvalidCommits: true
          excludeTypes: "docs,build,chore"
      -
        name: Create a release
        uses: action-pack/github-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag: "v${{ vars.MAJOR }}.${{ vars.MINOR }}"
          title: "v${{ vars.MAJOR }}.${{ vars.MINOR }}"
          commit: "release/v${{ vars.MAJOR }}.${{ vars.MINOR }}"
          body: |
            ${{ steps.changelog.outputs.changes }}

            **Full Changelog**: https://github.com/${{ github.repository }}/compare//${{ env.previousTag }}...v${{ vars.MAJOR }}.${{ vars.MINOR }}
      -
        name: Update major release
        uses: action-pack/github-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag: "v${{ vars.MAJOR }}"
          title: "v${{ vars.MAJOR }}"
          body: "See https://github.com/${{ github.repository }}/releases/tag/v${{ vars.MAJOR }}.${{ vars.MINOR }}"
          commit: "release/v${{ vars.MAJOR }}.${{ vars.MINOR }}"
      -
        name: Increment version variable
        uses: action-pack/bump@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
